services:
  backend:
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      ML_URL: ${ML_URL}
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - gradle-cache:/home/gradle/.gradle

  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: techtrack-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  elasticsearch:
    image: 11zzard/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports: [ "9200:9200" ]
    volumes: [ "esdata:/usr/share/elasticsearch/data" ]

  kibana:
    image: 11zzard/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${TOKEN}
      - xpack.security.enrollment.enabled=false
      - SERVER_BASEPATH=/logs
      - SERVER_REWRITEBASEPATH=true
      - SERVER_PUBLICBASEURL=https://techtrekgame.ru/logs
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    ports: [ "5601:5601" ]

  logstash:
    image: 11zzard/logstash:8.13.4
    container_name: logstash
    ports: [ "5000:5000" ]
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - xpack.monitoring.enabled=false


volumes:
  pgdata:
  esdata:
  gradle-cache:
