spring:
  application:
    name: startup-game
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET}

ml:
  base-url: ${ML_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

yandex:
  translate:
    api-key: ${YANDEX_API_KEY}
    folder-id: ${YANDEX_FOLDER_ID}
    endpoint: "https://translate.api.cloud.yandex.net/translate/v2/translate"

server:
  port: 8080