name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'docker-compose.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push frontend image
      working-directory: ./frontend
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/startup-game-frontend:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/startup-game-frontend:latest

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Login to Heroku
      run: |
        heroku container:login

    - name: Deploy to Heroku
      run: |
        heroku container:push web --app ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME_FRONTEND }}

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test
